### ISSUE TITLE
Having issues using SetTextData()

### ISSUE THREAD

**Issue by nhi-vanye** [PDFTron/pdftron-go#12]
I'm trying to use SetTextData() on an element to truncate the text string. I'd previously prototyped it in Python and that works...

In python I have

```
    element = reader.Next()
    data_ = element.GetTextData()
    element.SetTextData(data_[:brp], len(data_[:brp]) )
    writer.WriteElement(element)

```

With Go's GetTextData() returning a `VectorUnChar` not a slice what's the suggested approach, since none of the ones I've tried are working.

(interestingly, the `Size()` in VectorUnChar seems to contain a number twice the size of the number of characters in the string (from `GetTextString()`) so not sure how to iterate using `Get()`.

**Comment by nhi-vanye** [comment]
should use forum for community support

**Comment by rchennafi** [comment]
Closed since it sounds like this was taken to the community forums, which is likely the best place.
