### ISSUE TITLE
libPDFNetC.so does not support arm64 architecture for linux

### ISSUE THREAD

**Issue by Petromar88** [PDFTron/pdftron-go#15]
We are developing a Go microservice on macOS M1 machines which will be run on linux/amd64 based machines.
In order to be able to test it on local machines and build it for prod and pre-prod machines, we would like to create a docker image for linux/amd64 and linux/arm64 platforms using Earthly (which leverages golangci/golangci-lint as the base docker image) like we do for all of the other microservices.
As of now we are not able to do so because building PDFtron from a linux/arm64 docker image fails.

Could you please provide a unix/Lib/arm64 version of the library along with this package?

Thanks in advance!

**Comment by rchennafi** [comment]
As of version 2.2.5, this import should be included.
